backend:
  name: git-gateway
  branch: main

# (opcional) modo simple de publicaci칩n
publish_mode: simple
local_backend: false

# D칩nde se suben las im치genes desde el panel
media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  # ===== Ajustes generales (texto del hero, links, email) =====
  - name: "settings"
    label: "Ajustes"
    files:
      - file: "data/texts.json"
        label: "Textos y enlaces"
        name: "texts"
        format: "json"
        editor:
          preview: false
        fields:
          - { label: "T칤tulo Hero (HTML permitido)", name: "hero_title", widget: "text", default: "Decoraci칩n <span class='resaltado'>100% personalizada</span> para tu fiesta" }
          - { label: "Subt칤tulo Hero", name: "hero_sub", widget: "text", default: "Papeler칤a creativa, toppers con luz, pi침atas, letras 3D, bolsitas y souvenirs. Hecho con amor desde el alma 游눪" }
          - { label: "WhatsApp (link completo)", name: "whatsapp_link", widget: "string", default: "https://wa.me/5491167286443?text=Hola!%20Quiero%20cotizar%20mi%20cumple%20con%20Manos%20%26%20Magia%20Studio" }
          - { label: "Instagram (URL)", name: "instagram", widget: "string", default: "https://www.instagram.com/manosymagia_studio/" }
          - { label: "Email", name: "email", widget: "string", default: "manosymagiastudio@gmail.com" }

  # ===== Productos destacados =====
  - name: "products"
    label: "Productos"
    files:
      - file: "data/products.json"
        label: "Listado de productos"
        name: "products_list"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            fields:
              - { label: "T칤tulo", name: "title", widget: "string" }
              - { label: "Descripci칩n", name: "description", widget: "text", required: false }
              - { label: "Precio desde", name: "price_from", widget: "string", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }

  # ===== Combos de fiesta =====
  - name: "combos"
    label: "Combos de fiesta"
    files:
      - file: "data/combos.json"
        label: "Listado de combos"
        name: "combos_list"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Combos"
            name: "items"
            widget: "list"
            fields:
              - { label: "T칤tulo", name: "title", widget: "string" }
              - label: "칈tems del combo"
                name: "items"
                widget: "list"
                field: { label: "칈tem", name: "item", widget: "string" }
              - { label: "Precio", name: "price", widget: "string", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }

  # ===== Galer칤a =====
  - name: "gallery"
    label: "Galer칤a"
    files:
      - file: "data/gallery.json"
        label: "Fotos de galer칤a"
        name: "gallery_list"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Fotos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Imagen", name: "src", widget: "image" }
              - { label: "Alt (texto alternativo)", name: "alt", widget: "string", required: false }
