backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

logo_url: "/img/logo.png"

site_url: "https://manosymagiastudio.netlify.app"
display_url: "https://manosymagiastudio.netlify.app"

collections:
  # --- Ajustes del sitio ---
  - name: "settings"
    label: "⚙️ Ajustes del sitio"
    files:
      - file: "data/texts.json"
        label: "Textos y enlaces principales"
        name: "texts"
        format: "json"
        fields:
          - { label: "WhatsApp Link", name: "whatsapp_link", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Título principal (HTML)", name: "hero_title", widget: "text" }
          - { label: "Subtítulo principal", name: "hero_sub", widget: "text" }

  # --- Productos ---
  - name: "products"
    label: "🎁 Productos"
    files:
      - file: "data/products.json"
        label: "Listado de productos"
        name: "products"
        format: "json"
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            minimize_collapsed: true
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Precio", name: "price", widget: "string", required: false }
              - { label: "Etiquetas (tags)", name: "tags", widget: "list", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }
              - { label: "Link de WhatsApp (opcional)", name: "whatsapp", widget: "string", required: false }

  # --- Combos ---
  - name: "combos"
    label: "🎀 Combos de fiesta"
    files:
      - file: "data/combos.json"
        label: "Listado de combos"
        name: "combos"
        format: "json"
        fields:
          - label: "Combos"
            name: "items"
            widget: "list"
            minimize_collapsed: true
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Precio", name: "price", widget: "string", required: false }
              - { label: "Etiquetas (tags)", name: "tags", widget: "list", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }
              - { label: "Link de WhatsApp (opcional)", name: "whatsapp", widget: "string", required: false }
