backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  # Textos / links generales del sitio
  - name: "settings"
    label: "Ajustes del sitio"
    files:
      - file: "data/texts.json"
        label: "Textos y enlaces"
        name: "texts"
        format: "json"
        fields:
          - { label: "WhatsApp Link", name: "whatsapp_link", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Título Hero (HTML)", name: "hero_title", widget: "text" }
          - { label: "Subtítulo Hero", name: "hero_sub", widget: "text" }

  # Productos (un único JSON con lista)
  - name: "products"
    label: "Productos"
    files:
      - file: "data/products.json"
        label: "Listado de productos"
        name: "products"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            minimize_collapsed: true
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Precio", name: "price", widget: "string", required: false }
              - { label: "Tags", name: "tags", widget: "list", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }
              - { label: "WhatsApp URL (opcional)", name: "whatsapp", widget: "string", required: false }

  # Combos (otro JSON con lista)
  - name: "combos"
    label: "Combos"
    files:
      - file: "data/combos.json"
        label: "Listado de combos"
        name: "combos"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            minimize_collapsed: true
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Precio", name: "price", widget: "string", required: false }
              - { label: "Tags", name: "tags", widget: "list", required: false }
              - { label: "Imagen", name: "image", widget: "image", required: false }
              - { label: "WhatsApp URL (opcional)", name: "whatsapp", widget: "string", required: false }
